// yellow: title, white: verses, green: pre-chorus, blue: chorus, red: post-chorus
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("TIGHTROPE - ZAYN");
Console.ResetColor();
Console.WriteLine("Why's it gotta feel like I'm walkin' a tightrope?");
Console.WriteLine("Why you wanna see how far I fall?");
Console.WriteLine("'Cause I'm already up here and I got my eyes closed");
Console.WriteLine("And I ain't never fell from a love this tall");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Are you ready? 'Cause I'm ready to let go");
Console.WriteLine("Never thought that I'd be ready again");
Console.WriteLine("Guess there's somethin' 'bout the neon red glow");
Console.WriteLine("Got me thinkin' 'bout givin' all in");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.ResetColor();
Console.WriteLine("I'm sittin' with my legs across your torso");
Console.WriteLine("We are who we are when we're alone");
Console.WriteLine("Baby, I'm ready, any minute, we might fall");
Console.WriteLine("Lately, I feel like my grip is gone");
Console.WriteLine("But you got my arm");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Are you ready? 'Cause I'm ready to let go");
Console.WriteLine("Never thought that I'd be ready again");
Console.WriteLine("Guess there's somethin' 'bout the neon red glow");
Console.WriteLine("Got me thinkin' 'bout givin' all in");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Are you the full moon or the sun?");
Console.WriteLine("Whatever you are, I swear to God, you are beyond compare");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.WriteLine("Somethin' told me it was you");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Are you the full moon or the sun?");
Console.WriteLine("Whatever you are, I swear to God, you are beyond compare");